EXTINGUISHER = "EXTINGUISHER"
HYDRANT = "HYDRANT"
SMOKE_DETECTOR = "SMOKE_DETECTOR"
SPRINKLER = "SPRINKLER"
EXIT_LIGHT = "EXIT_LIGHT"

DeviceType = [EXTINGUISHER, HYDRANT, SMOKE_DETECTOR, SPRINKLER, EXIT_LIGHT]

DEVICE_TYPE_LABELS = {
    EXTINGUISHER: "灭火器",
    HYDRANT: "消火栓",
    SMOKE_DETECTOR: "烟感探测器",
    SPRINKLER: "喷淋头",
    EXIT_LIGHT: "疏散指示灯",
}
