PLANNED = "PLANNED"
IN_PROGRESS = "IN_PROGRESS"
SUBMITTED = "SUBMITTED"
REVIEWED = "REVIEWED"
OVERDUE = "OVERDUE"

InspectionStatus = [PLANNED, IN_PROGRESS, SUBMITTED, REVIEWED, OVERDUE]

INSPECTION_STATUS_LABELS = {
    PLANNED: "待领取",
    IN_PROGRESS: "巡检中",
    SUBMITTED: "待复验",
    REVIEWED: "已复核",
    OVERDUE: "已逾期",
}

# 任务终态：终态任务不再接受任何巡检结果提交（并发提交只能落一份）。
CLOSED_TASK_STATUSES = [SUBMITTED, REVIEWED, OVERDUE]
