ROLE_INSPECTOR = "INSPECTOR"          # 巡检员
ROLE_MAINTAINER = "MAINTAINER"        # 维保人员
ROLE_SUPERVISOR = "SUPERVISOR"        # 物业主管
ROLE_AUDITOR = "AUDITOR"              # 审计员

ROLES = [ROLE_INSPECTOR, ROLE_MAINTAINER, ROLE_SUPERVISOR, ROLE_AUDITOR]

ROLE_LABELS = {
    ROLE_INSPECTOR: "巡检员",
    ROLE_MAINTAINER: "维保人员",
    ROLE_SUPERVISOR: "物业主管",
    ROLE_AUDITOR: "审计员",
}
